begin
   begin
      execute immediate 'alter table investment_instrument_type rename column investment_id to instrument_type_id';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table investment_instrument_type rename column investment_type to instrument_type';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table investment_instrument_type rename column investment_desc to instrument_type_desc';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table investment_instrument_type rename to instrument_type';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table investment_details rename column type to investment_type';
   exception
      when others then
         null;
   end;
end;
/

begin
-- Customer Table
   begin
      execute immediate 'create table customer (
                                            user_id    number
                                                generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 64 cache 20
                                                noorder nocycle nokeep noscale
                                            not null enable,
                                            user_name  varchar2(1000 char),
                                            password   varchar2(1000 char),
                                            first_name varchar2(1000 char),
                                            last_name  varchar2(1000 char),
                                            dob        varchar2(20 byte),
                                            gender     varchar2(10 char),
                                            phone_nbr  number,
                                            email      varchar2(1000 char),
                                            pin_code   number,
                                            city       varchar2(100 char),
                                            address    varchar2(2000 char),
                                            created_at date default sysdate
                                          )
                                          segment creation immediate';
   exception
      when others then
         null;
   end;
end;
/


begin
   begin
      begin
         execute immediate 'alter table account_holder add (user_id number)';
      exception
         when others then
            null;
      end;
      begin
         execute immediate 'alter table account_holder set unused ( first_name,
                                        last_name,
                                        address,
                                        pin_code,
                                        phone_nbr,
                                        email )';
      exception
         when others then
            null;
      end;
      begin
         execute immediate 'alter table account_holder drop unused columns';
      exception
         when others then
            null;
      end;
   end;

   begin
      execute immediate 'alter table bank_master modify (city varchar2(50))';
   exception
      when others then
         null;
   end;
   declare
      lv_max number;
   begin
      select nvl(
         max(investment_id),
         0
      )
        into lv_max
        from investment_details;

      lv_max := lv_max + 1;
      execute immediate 'alter table investment_details 
   modify (investment_id  generated by default as identity
    (start with '
                        || lv_max
                        || '
    increment by 1
    ))';
      select nvl(
         max(user_id),
         0
      )
        into lv_max
        from customer;

      lv_max := lv_max + 1;
      execute immediate 'alter table customer modify ( USER_ID number generated by default as identity
    (start with '
                        || lv_max
                        || '
    increment by 1
    ))';
      select nvl(
         max(instrument_type_id),
         0
      )
        into lv_max
        from instrument_type;

      lv_max := lv_max + 1;
      execute immediate 'alter table instrument_type modify ( instrument_type_id number generated by default as identity
    (start with '
                        || lv_max
                        || '
    increment by 1
    ))';
   end;
end;
/