begin
   begin
      --  Debug table
      execute immediate 'create table debug_tab (attr varchar2(4000), created_at date default sysdate)';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table debug_tab modify (attr not null enable)';
   exception
      when others then
         null;
   end;
   begin
  -- Bank Master Table
      execute immediate 'create table bank_master (
                                      bank_name   varchar2(40 byte) not null enable,
                                      branch_name varchar2(100 byte) not null enable,
                                      city        varchar2(50 byte) default ''BENGALURU'' not null enable,
                                      pin         number,
                                      bank_abbr   varchar2(20 byte) not null enable,
                                      bank_id     number
                                          generated by default on null as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 1 cache
                                          20 noorder nocycle nokeep noscale
                                      not null enable,
                                      created_at date default sysdate
                                    )
                                    segment creation immediate';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'create unique index bank_master_pk on
                                                    bank_master (
                                                        bank_id
                                                    )';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table bank_master
                            add constraint bank_master_pk primary key ( bank_id )
                                using index bank_master_pk enable';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'create table instrument_type (
                                      instrument_type_id   number
                                          generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 62 cache 20
                                          noorder nocycle nokeep noscale
                                      not null enable,
                                      instrument_type      varchar2(10 byte) not null enable,
                                      instrument_type_desc varchar2(100 byte),
                                      created_at date default sysdate
                                    )
                                    segment creation immediate';
   exception
      when others then
         null;
   end;


-- Instrument Type Table
   begin
      execute immediate 'create unique index investment_instrument_type_pk on
                                                    instrument_type (
                                                        instrument_type_id
                                                    )';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'create unique index investment_instrument_type_unq on
                                              instrument_type (
                                                  instrument_type
                                              )';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table instrument_type
                                    add constraint investment_instrument_type_pk primary key ( instrument_type_id )
                                        using index investment_instrument_type_pk enable';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table instrument_type
                                      add constraint investment_instrument_type_unq unique ( instrument_type )
                                          using index investment_instrument_type_unq enable';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'comment on table instrument_type is ''Contains the types of instrument types''';
   exception
      when others then
         null;
   end; 

-- Customer Table
   begin
      execute immediate 'create table customer (
                                            user_id    number
                                                generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 64 cache 20
                                                noorder nocycle nokeep noscale
                                            not null enable,
                                            user_name  varchar2(1000 char),
                                            password   varchar2(1000 char),
                                            first_name varchar2(1000 char),
                                            last_name  varchar2(1000 char),
                                            dob        varchar2(20 byte),
                                            gender     varchar2(10 char),
                                            phone_nbr  number,
                                            email      varchar2(1000 char),
                                            pin_code   number,
                                            city       varchar2(100 char),
                                            address    varchar2(2000 char),
                                            created_at date default sysdate
                                          )
                                          segment creation immediate';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'create unique index customer_user_id_pk on
                                                    customer (
                                                        user_id)';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table customer add constraint customer_user_id_pk primary key  (user_id) using 
                           index customer_user_id_pk';
   exception
      when others then
         null;
   end;
-- Account Holder Table

   begin
      execute immediate 'create table account_holder (
                                          account_nbr    number not null enable,
                                          preferred_name varchar2(40) not null enable,
                                          bank_id        number,
                                          user_id        number,
                                          created_at date default sysdate
                                        )
                                        segment creation immediate';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'create unique index account_holder_pk on
                                                        account_holder (
                                                            account_nbr
                                                        )';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table account_holder
                                          add constraint account_holder_pk primary key ( account_nbr )
                                              using index account_holder_pk enable';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'comment on table account_holder is ''Contains the account holders'' information''';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table account_holder add constraint acctholder$userid$fk foreign key ( user_id )
                                              references customer ( user_id )
                                                on delete cascade enable';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table account_holder add constraint acctholder$bankid$fk foreign key ( bank_id )
                                              references bank_master ( bank_id )
                                                on delete cascade enable';
   exception
      when others then
         null;
   end;                                                

   -- Instrument Details
   begin
      execute immediate 'create table investment_details (
                                        investment_id         number
                                            generated by default as identity minvalue 1 maxvalue 9999999999999999999999999999 increment by 1 start with 184 cache 20
                                            noorder nocycle nokeep noscale
                                        not null enable,
                                        account_nbr           number not null enable,
                                        instrument_type       varchar2(10 byte) not null enable,
                                        instrument_id         varchar2(100 byte) not null enable,
                                        instrument_name       varchar2(100 byte) not null enable,
                                        instrument_assoc_bank varchar2(100 byte) not null enable,
                                        investment_amt        number not null enable,
                                        investment_dt         date not null enable,
                                        instrument_closed_dt  date,
                                        active_flag           varchar2(1 char) default ''Y'' not null enable,
                                        investment_type       varchar2(10 byte) default ''SIP'',
                                        constraint invtdtls$acctnbr$fk foreign key ( account_nbr )
                                            references account_holder ( account_nbr )
                                        enable,
                                        created_at date default sysdate
                                      )
                                      segment creation immediate';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'create unique index investment_details_pk on
                                                  investment_details (
                                                      investment_id
                                                  )';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'alter table investment_details
                                            add constraint investment_details_pk primary key ( investment_id )
                                                using index investment_details_pk enable';
   exception
      when others then
         null;
   end;
   begin
      execute immediate 'comment on table investment_details is 
          ''Stores the investment details for an account (combination of user, bank and branch.)''';
   exception
      when others then
         null;
   end;
end;
/